version: '3.8'

services:
  bot:
    build: .
    container_name: ${PERSONA}-persona-bot
    environment:
      ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      RANDOM_ENCOUNTER_CHANCE: ${RANDOM_ENCOUNTER_CHANCE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BOT_ROLE: ${BOT_ROLE}
      BOT_PERSONALITY: ${BOT_PERSONALITY}
      BOT_WORDS_LIST: ${BOT_WORDS_LIST}
